config: # preconfigged for 2560x1440
    Screenshot:
        position_coords:
            position_x: 730
            position_y: 1120
        screenshot_size:
            width: 1100
            height: 250
    ColorizeThresholds: # making grayscale with openCV for further recognition
        top: 230 # name of NPC
        bot: 30  # text
    CuttingRectangles: # cutting name and text on rectangles
        rectangle_coords:
            top_x: 50
            top_y: 10
            bot_x: 50
            bot_y: 67
        rectangle_size:
            top_x: 300
            top_y: 50
            bot_x: 1000
            bot_y: 160
    DialogFrameDetection: # which pixel to check
        pixel_coords_x: 20
        pixel_coords_y: 150
    DialogFrameColors: # color values of pixel in different types of dialogs, 4th item means that dialog without HUD
        - [201, 217, 226, 0]
        - [159, 177, 191, 0]
        - [190, 210, 217, 0]
        #- [74, 36, 14, 0]
        - [8, 15, 19, 0]
        - [0, 0, 0, 0]
        - [202, 219, 228, 1]
        - [199, 216, 231, 1]
        - [200, 181, 168, 1]
        - [105, 113, 115, 1]
        - [106, 114, 115, 1]
        - [0, 0, 0, 1]
    CuttingCorrection: # when dialog without HUD
        shift_y: 23
        debug: false
    Translation:
        from: en
        to: ru
        translator: ggl
